import datetime
from sqlalchemy.orm import Session
from app.models.title import Title, Genre


SEED_GENRES = [
    "Sci-Fi", "Drama", "Action", "Thriller", "Comedy",
    "Crime", "Adventure", "Animation", "Romance", "Mystery",
    "Horror", "Fantasy"
]

SEED_TITLES = [
    {
        "title": "Interstellar",
        "type": "movie",
        "overview": "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
        "release_date": datetime.date(2014, 11, 7),
        "runtime_minutes": 169,
        "vote_average": 8.4,
        "vote_count": 34000,
        "popularity": 92.5,
        "director": "Christopher Nolan",
        "cast_members": "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
        "poster_path": "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/rAiYTsqJJR0KP845946iFvNXY5r.jpg",
        "genres": ["Sci-Fi", "Drama", "Adventure"],
    },
    {
        "title": "Blade Runner 2049",
        "type": "movie",
        "overview": "Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos.",
        "release_date": datetime.date(2017, 10, 6),
        "runtime_minutes": 164,
        "vote_average": 8.0,
        "vote_count": 13000,
        "popularity": 85.0,
        "director": "Denis Villeneuve",
        "cast_members": "Ryan Gosling, Harrison Ford, Ana de Armas",
        "poster_path": "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/sAtoMqDVhNDQBc3QJL3RF6hlxGq.jpg",
        "genres": ["Sci-Fi", "Drama", "Mystery"],
    },
    {
        "title": "Parasite",
        "type": "movie",
        "overview": "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
        "release_date": datetime.date(2019, 5, 30),
        "runtime_minutes": 132,
        "vote_average": 8.5,
        "vote_count": 17500,
        "popularity": 88.0,
        "director": "Bong Joon-ho",
        "cast_members": "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong",
        "poster_path": "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
        "genres": ["Drama", "Thriller", "Comedy"],
    },
    {
        "title": "Knives Out",
        "type": "movie",
        "overview": "When renowned crime novelist Harlan Thrombey is found dead at his estate, the inquisitive and debonair Detective Benoit Blanc is mysteriously enlisted to investigate.",
        "release_date": datetime.date(2019, 11, 27),
        "runtime_minutes": 130,
        "vote_average": 7.9,
        "vote_count": 12000,
        "popularity": 78.4,
        "director": "Rian Johnson",
        "cast_members": "Daniel Craig, Chris Evans, Ana de Armas",
        "poster_path": "https://image.tmdb.org/t/p/w500/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg",
        "genres": ["Mystery", "Comedy", "Crime"],
    },
    {
        "title": "Spider-Man: Into the Spider-Verse",
        "type": "movie",
        "overview": "Teen Miles Morales becomes the new Spider-Man and joins other Spider-Heroes from various parallel universes to stop a threat to all reality.",
        "release_date": datetime.date(2018, 12, 14),
        "runtime_minutes": 117,
        "vote_average": 8.4,
        "vote_count": 15000,
        "popularity": 94.0,
        "director": "Bob Persichetti, Peter Ramsey, Rodney Rothman",
        "cast_members": "Shameik Moore, Jake Johnson, Hailee Steinfeld",
        "poster_path": "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/7d6o006fO1J10640f0fSj4aP4q.jpg",
        "genres": ["Animation", "Action", "Adventure", "Sci-Fi"],
    },
    {
        "title": "Whiplash",
        "type": "movie",
        "overview": "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, testing his physical and mental limits.",
        "release_date": datetime.date(2014, 10, 10),
        "runtime_minutes": 107,
        "vote_average": 8.4,
        "vote_count": 14500,
        "popularity": 81.0,
        "director": "Damien Chazelle",
        "cast_members": "Miles Teller, J.K. Simmons, Paul Reiser",
        "poster_path": "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/6bbZ6XyvgfjhC0lnRFx3AioOP0r.jpg",
        "genres": ["Drama"],
    },
    {
        "title": "The Grand Budapest Hotel",
        "type": "movie",
        "overview": "The adventures of Gustave H, a legendary concierge at a famous European hotel between the wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.",
        "release_date": datetime.date(2014, 3, 28),
        "runtime_minutes": 99,
        "vote_average": 8.0,
        "vote_count": 14000,
        "popularity": 75.0,
        "director": "Wes Anderson",
        "cast_members": "Ralph Fiennes, F. Murray Abraham, Mathieu Amalric",
        "poster_path": "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWX9NZkt5N2.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/foc5RcsdKz32B5F1q3w8xH8Z4f.jpg",
        "genres": ["Comedy", "Drama", "Adventure"],
    },
    {
        "title": "Dune: Part Two",
        "type": "movie",
        "overview": "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
        "release_date": datetime.date(2024, 3, 1),
        "runtime_minutes": 166,
        "vote_average": 8.6,
        "vote_count": 6000,
        "popularity": 99.0,
        "director": "Denis Villeneuve",
        "cast_members": "Timothée Chalamet, Zendaya, Rebecca Ferguson",
        "poster_path": "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0x2.jpg",
        "genres": ["Sci-Fi", "Adventure", "Drama"],
    },
    {
        "title": "The Dark Knight",
        "type": "movie",
        "overview": "Batman raises the stakes in his war on crime with the help of Lt. Jim Gordon and District Attorney Harvey Dent, but the Joker unleashes anarchy upon Gotham City.",
        "release_date": datetime.date(2008, 7, 18),
        "runtime_minutes": 152,
        "vote_average": 9.0,
        "vote_count": 32000,
        "popularity": 96.0,
        "director": "Christopher Nolan",
        "cast_members": "Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine",
        "poster_path": "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
        "genres": ["Action", "Crime", "Drama", "Thriller"],
    },
    {
        "title": "Inception",
        "type": "movie",
        "overview": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
        "release_date": datetime.date(2010, 7, 16),
        "runtime_minutes": 148,
        "vote_average": 8.4,
        "vote_count": 36000,
        "popularity": 91.0,
        "director": "Christopher Nolan",
        "cast_members": "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page, Tom Hardy",
        "poster_path": "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
        "genres": ["Action", "Sci-Fi", "Adventure"],
    },
    {
        "title": "Spirited Away",
        "type": "movie",
        "overview": "A sullen ten-year-old girl wanders into a world ruled by gods, witches, and spirits, where humans are changed into beasts.",
        "release_date": datetime.date(2001, 7, 20),
        "runtime_minutes": 125,
        "vote_average": 8.5,
        "vote_count": 16000,
        "popularity": 87.0,
        "director": "Hayao Miyazaki",
        "cast_members": "Rumi Hiiragi, Miyu Irino, Mari Natsuki",
        "poster_path": "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg",
        "genres": ["Animation", "Fantasy", "Adventure", "Drama"],
    },
    {
        "title": "Pulp Fiction",
        "type": "movie",
        "overview": "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        "release_date": datetime.date(1994, 9, 10),
        "runtime_minutes": 154,
        "vote_average": 8.5,
        "vote_count": 27000,
        "popularity": 89.0,
        "director": "Quentin Tarantino",
        "cast_members": "John Travolta, Samuel L. Jackson, Uma Thurman, Bruce Willis",
        "poster_path": "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
        "genres": ["Crime", "Thriller", "Drama"],
    },
    {
        "title": "Arrival",
        "type": "movie",
        "overview": "Taking place after alien spacecraft touch down across the globe, a linguistics professor is recruited by the military to assist in translating alien communications.",
        "release_date": datetime.date(2016, 11, 11),
        "runtime_minutes": 116,
        "vote_average": 7.9,
        "vote_count": 17000,
        "popularity": 83.0,
        "director": "Denis Villeneuve",
        "cast_members": "Amy Adams, Jeremy Renner, Forest Whitaker",
        "poster_path": "https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/yIZ1xendyqKvY3FGsqemmfd5YOG.jpg",
        "genres": ["Sci-Fi", "Drama", "Mystery"],
    },
    {
        "title": "Breaking Bad",
        "type": "series",
        "overview": "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's financial future.",
        "release_date": datetime.date(2008, 1, 20),
        "runtime_minutes": 47,
        "vote_average": 8.9,
        "vote_count": 14000,
        "popularity": 98.0,
        "director": "Vince Gilligan",
        "cast_members": "Bryan Cranston, Aaron Paul, Anna Gunn, Dean Norris",
        "poster_path": "https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
        "genres": ["Crime", "Drama", "Thriller"],
    },
    {
        "title": "Succession",
        "type": "series",
        "overview": "The Roy family is known for controlling the biggest media and entertainment company in the world. However, their world changes when their aging father steps down from the company.",
        "release_date": datetime.date(2018, 6, 3),
        "runtime_minutes": 60,
        "vote_average": 8.6,
        "vote_count": 3500,
        "popularity": 92.0,
        "director": "Jesse Armstrong",
        "cast_members": "Brian Cox, Jeremy Strong, Sarah Snook, Kieran Culkin",
        "poster_path": "https://image.tmdb.org/t/p/w500/7udW8s5vJg35c1K3yFp5v2Qk3.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/e9QbocXmjqZceS68k7GgQd3U1r1.jpg",
        "genres": ["Drama"],
    },
    {
        "title": "Stranger Things",
        "type": "series",
        "overview": "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
        "release_date": datetime.date(2016, 7, 15),
        "runtime_minutes": 50,
        "vote_average": 8.6,
        "vote_count": 16500,
        "popularity": 97.0,
        "director": "The Duffer Brothers",
        "cast_members": "Millie Bobby Brown, Finn Wolfhard, Winona Ryder, David Harbour",
        "poster_path": "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
        "genres": ["Sci-Fi", "Drama", "Mystery"],
    },
    {
        "title": "Severance",
        "type": "series",
        "overview": "Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives. When a mysterious colleague appears outside of work, it begins a journey to discover the truth.",
        "release_date": datetime.date(2022, 2, 18),
        "runtime_minutes": 55,
        "vote_average": 8.4,
        "vote_count": 2200,
        "popularity": 89.0,
        "director": "Ben Stiller",
        "cast_members": "Adam Scott, Patricia Arquette, John Turturro, Christopher Walken",
        "poster_path": "https://image.tmdb.org/t/p/w500/p1su199UQ1X4pUa879mO6Q98z43.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/9i3yF46Kk2wL0A8t0g9r1x8y7.jpg",
        "genres": ["Sci-Fi", "Drama", "Thriller", "Mystery"],
    },
    # --- BOLLYWOOD & INDIAN CINEMA MASTERPIECES ---
    {
        "title": "3 Idiots",
        "type": "movie",
        "overview": "Two friends embark on a quest for a lost buddy. On this journey, they encounter a long forgotten bet, a wedding they must crash, and a funeral that goes impossibly out of control, recalling their college memories.",
        "release_date": datetime.date(2009, 12, 25),
        "runtime_minutes": 170,
        "vote_average": 8.5,
        "vote_count": 12500,
        "popularity": 92.0,
        "director": "Rajkumar Hirani",
        "cast_members": "Aamir Khan, R. Madhavan, Sharman Joshi, Kareena Kapoor, Boman Irani",
        "poster_path": "https://image.tmdb.org/t/p/w500/66A9MqXOyVFCssoloscw79z8swq.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/u7kuO05k5ZtV9x4pXpU5iK2Zf9Q.jpg",
        "genres": ["Comedy", "Drama"],
        "keywords": "Bollywood, Indian Cinema, Hindi, College, Friendship, Feel-Good",
    },
    {
        "title": "Zindagi Na Milegi Dobara",
        "type": "movie",
        "overview": "Three friends take a road trip across Spain before one of them gets married, facing their deepest fears, learning to let go of the past, and embracing life in the present moment.",
        "release_date": datetime.date(2011, 7, 15),
        "runtime_minutes": 155,
        "vote_average": 8.2,
        "vote_count": 8900,
        "popularity": 87.0,
        "director": "Zoya Akhtar",
        "cast_members": "Hrithik Roshan, Farhan Akhtar, Abhay Deol, Katrina Kaif, Kalki Koechlin",
        "poster_path": "https://image.tmdb.org/t/p/w500/mY0mN3r6P7kCkhwD3p1Zg6nE0jX.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/t5M2eM6p1K8b6V7oX9b5m7m7m7m.jpg",
        "genres": ["Comedy", "Drama", "Adventure"],
        "keywords": "Bollywood, Indian Cinema, Hindi, Road Trip, Friendship, Chill, Feel-Good",
    },
    {
        "title": "Dangal",
        "type": "movie",
        "overview": "Former wrestler Mahavir Singh Phogat trains his daughters Geeta and Babita to become world-class wrestlers, overcoming fierce societal prejudice to bring home international glory.",
        "release_date": datetime.date(2016, 12, 23),
        "runtime_minutes": 161,
        "vote_average": 8.4,
        "vote_count": 11000,
        "popularity": 90.0,
        "director": "Nitesh Tiwari",
        "cast_members": "Aamir Khan, Fatima Sana Shaikh, Sanya Malhotra, Sakshi Tanwar",
        "poster_path": "https://image.tmdb.org/t/p/w500/pI97eJvGq9oX7vK3p8b6V7oX9b5.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/eG8uQ5k1K9b6V7oX9b5m7m7m7m7.jpg",
        "genres": ["Drama", "Action"],
        "keywords": "Bollywood, Indian Cinema, Hindi, Wrestling, Inspiring, Sports",
    },
    {
        "title": "Andhadhun",
        "type": "movie",
        "overview": "A visually impaired pianist unwittingly becomes embroiled in the murder of an erstwhile film star, descending into a spiral of deceit, organ trafficking, and wicked surprises.",
        "release_date": datetime.date(2018, 10, 5),
        "runtime_minutes": 139,
        "vote_average": 8.3,
        "vote_count": 9200,
        "popularity": 88.0,
        "director": "Sriram Raghavan",
        "cast_members": "Ayushmann Khurrana, Tabu, Radhika Apte, Anil Dhawan",
        "poster_path": "https://image.tmdb.org/t/p/w500/dyhaB19AIC4PkYQ2YvlZ2Ci9fCe.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/aT3M9k1K8b6V7oX9b5m7m7m7m7m.jpg",
        "genres": ["Thriller", "Crime", "Comedy"],
        "keywords": "Bollywood, Indian Cinema, Hindi, Dark Comedy, Mind-Bending, Twists",
    },
    {
        "title": "Tumbbad",
        "type": "movie",
        "overview": "In 19th-century Maharashtra, a man's greed leads him to a forbidden treasure guarded by Hastar, a demonic entity, triggering a multi-generational curse.",
        "release_date": datetime.date(2018, 10, 12),
        "runtime_minutes": 104,
        "vote_average": 8.2,
        "vote_count": 7800,
        "popularity": 86.0,
        "director": "Rahi Anil Barve",
        "cast_members": "Sohum Shah, Jyoti Malshe, Anita Date, Ronjini Chakraborty",
        "poster_path": "https://image.tmdb.org/t/p/w500/y6p0N3r6P7kCkhwD3p1Zg6nE0jX.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/b9M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "genres": ["Horror", "Fantasy", "Drama"],
        "keywords": "Bollywood, Indian Cinema, Hindi, Mythology, Dark Suspense, Atmospheric",
    },
    {
        "title": "Gangs of Wasseypur",
        "type": "movie",
        "overview": "A clash between Sultan and Shahid Khan leads to the expulsion of Khan from Wasseypur, unleashing a deadly fifty-year blood feud spanning three generations of ruthless coal-mafia gangsters.",
        "release_date": datetime.date(2012, 6, 22),
        "runtime_minutes": 160,
        "vote_average": 8.2,
        "vote_count": 8400,
        "popularity": 85.0,
        "director": "Anurag Kashyap",
        "cast_members": "Manoj Bajpayee, Nawazuddin Siddiqui, Richa Chadha, Tigmanshu Dhulia, Huma Qureshi",
        "poster_path": "https://image.tmdb.org/t/p/w500/c7k1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/d8M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "genres": ["Crime", "Action", "Drama"],
        "keywords": "Bollywood, Indian Cinema, Hindi, Gangster, Dark Suspense, Gritty",
    },
    {
        "title": "Dil Chahta Hai",
        "type": "movie",
        "overview": "Three inseparable college friends navigate romance, transition into adulthood, and the strain that divergent values place on their cherished brotherhood in Goa and Mumbai.",
        "release_date": datetime.date(2001, 8, 10),
        "runtime_minutes": 183,
        "vote_average": 8.1,
        "vote_count": 7500,
        "popularity": 82.0,
        "director": "Farhan Akhtar",
        "cast_members": "Aamir Khan, Saif Ali Khan, Akshaye Khanna, Preity Zinta, Dimple Kapadia",
        "poster_path": "https://image.tmdb.org/t/p/w500/e9M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/f1M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "genres": ["Comedy", "Drama", "Romance"],
        "keywords": "Bollywood, Indian Cinema, Hindi, Cult, Friendship, Chill",
    },
    {
        "title": "Taare Zameen Par",
        "type": "movie",
        "overview": "An imaginative eight-year-old boy struggles silently with dyslexia until an empathetic and unorthodox art teacher discovers his creative brilliance and guides him forward.",
        "release_date": datetime.date(2007, 12, 21),
        "runtime_minutes": 165,
        "vote_average": 8.4,
        "vote_count": 9900,
        "popularity": 86.0,
        "director": "Aamir Khan",
        "cast_members": "Aamir Khan, Darsheel Safary, Tisca Chopra, Vipin Sharma",
        "poster_path": "https://image.tmdb.org/t/p/w500/h2M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/j3M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "genres": ["Drama"],
        "keywords": "Bollywood, Indian Cinema, Hindi, Emotional, Feel-Good, Family",
    },
    {
        "title": "Queen",
        "type": "movie",
        "overview": "After her conservative fiancé calls off their wedding days before the ceremony, Rani embarks alone on her pre-booked Paris and Amsterdam honeymoon, discovering self-love and independence.",
        "release_date": datetime.date(2014, 3, 7),
        "runtime_minutes": 144,
        "vote_average": 8.2,
        "vote_count": 7900,
        "popularity": 84.0,
        "director": "Vikas Bahl",
        "cast_members": "Kangana Ranaut, Rajkummar Rao, Lisa Haydon",
        "poster_path": "https://image.tmdb.org/t/p/w500/k4M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/l5M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "genres": ["Comedy", "Drama", "Adventure"],
        "keywords": "Bollywood, Indian Cinema, Hindi, Solo, Travel, Feel-Good",
    },
    {
        "title": "Drishyam",
        "type": "movie",
        "overview": "When the son of an unyielding Inspector General of Police goes missing after harassing a cable operator's daughter, the street-smart father constructs an ironclad alibi to protect his family.",
        "release_date": datetime.date(2015, 7, 31),
        "runtime_minutes": 163,
        "vote_average": 8.3,
        "vote_count": 9100,
        "popularity": 88.0,
        "director": "Nishikant Kamat",
        "cast_members": "Ajay Devgn, Tabu, Shriya Saran, Rajat Kapoor",
        "poster_path": "https://image.tmdb.org/t/p/w500/m6M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/n7M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "genres": ["Crime", "Thriller", "Mystery"],
        "keywords": "Bollywood, Indian Cinema, Hindi, Mind-Bending, Suspense, Family",
    },
    {
        "title": "Barfi!",
        "type": "movie",
        "overview": "Set in 1970s Darjeeling and Kolkata, Barfi, a mute and hearing-impaired young man, forms poignant, joyous bonds with two distinct women: Shruti and Jhilmil, an autistic heiress.",
        "release_date": datetime.date(2012, 9, 14),
        "runtime_minutes": 151,
        "vote_average": 8.1,
        "vote_count": 7300,
        "popularity": 83.0,
        "director": "Anurag Basu",
        "cast_members": "Ranbir Kapoor, Priyanka Chopra, Ileana D'Cruz, Saurabh Shukla",
        "poster_path": "https://image.tmdb.org/t/p/w500/o8M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/p9M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "genres": ["Comedy", "Drama", "Romance"],
        "keywords": "Bollywood, Indian Cinema, Hindi, Whimsical, Feel-Good, Romance",
    },
    {
        "title": "Chhichhore",
        "type": "movie",
        "overview": "Following a family tragedy, a middle-aged father reunites with his college hostel buddies to recount their days as notorious 'losers', reminding his son that resilience triumphs over failure.",
        "release_date": datetime.date(2019, 9, 6),
        "runtime_minutes": 143,
        "vote_average": 8.2,
        "vote_count": 8200,
        "popularity": 85.0,
        "director": "Nitesh Tiwari",
        "cast_members": "Sushant Singh Rajput, Shraddha Kapoor, Varun Sharma, Tahir Raj Bhasin",
        "poster_path": "https://image.tmdb.org/t/p/w500/q1M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/r2M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "genres": ["Comedy", "Drama"],
        "keywords": "Bollywood, Indian Cinema, Hindi, College, Friendship, Feel-Good",
    },
    {
        "title": "Stree",
        "type": "movie",
        "overview": "In the small town of Chanderi, men mysteriously disappear during an annual religious festival, abducted by an angry female spirit called 'Stree' who whispers their names in the dark.",
        "release_date": datetime.date(2018, 8, 31),
        "runtime_minutes": 128,
        "vote_average": 7.8,
        "vote_count": 7100,
        "popularity": 83.0,
        "director": "Amar Kaushik",
        "cast_members": "Rajkummar Rao, Shraddha Kapoor, Pankaj Tripathi, Aparshakti Khurana",
        "poster_path": "https://image.tmdb.org/t/p/w500/s3M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/t4M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "genres": ["Comedy", "Horror"],
        "keywords": "Bollywood, Indian Cinema, Hindi, Horror Comedy, Chill, Friends",
    },
    {
        "title": "Kahaani",
        "type": "movie",
        "overview": "A pregnant software engineer arrives in Kolkata from London during the vibrant Durga Puja festival, relentlessly seeking her missing husband despite bureaucratic gaslighting.",
        "release_date": datetime.date(2012, 3, 9),
        "runtime_minutes": 122,
        "vote_average": 8.1,
        "vote_count": 7400,
        "popularity": 82.0,
        "director": "Sujoy Ghosh",
        "cast_members": "Vidya Balan, Parambrata Chatterjee, Nawazuddin Siddiqui, Saswata Chatterjee",
        "poster_path": "https://image.tmdb.org/t/p/w500/u5M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/v6M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "genres": ["Thriller", "Mystery"],
        "keywords": "Bollywood, Indian Cinema, Hindi, Dark Suspense, Kolkata, Twists",
    },
    {
        "title": "Jab We Met",
        "type": "movie",
        "overview": "A despondent, heartbroken Mumbai industrialist boards a train aimlessly and meets a bubbly, chatterbox Punjabi girl, turning his worldview upside down on an accidental journey.",
        "release_date": datetime.date(2007, 10, 26),
        "runtime_minutes": 138,
        "vote_average": 7.9,
        "vote_count": 6800,
        "popularity": 81.0,
        "director": "Imtiaz Ali",
        "cast_members": "Shahid Kapoor, Kareena Kapoor, Tarun Arora, Dara Singh",
        "poster_path": "https://image.tmdb.org/t/p/w500/w7M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/x8M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "genres": ["Romance", "Comedy", "Drama"],
        "keywords": "Bollywood, Indian Cinema, Hindi, Romantic Comedy, Feel-Good, Chill",
    },
    {
        "title": "Piku",
        "type": "movie",
        "overview": "A quirky road trip from Delhi to Kolkata unfolds between a busy architect daughter, her hypochondriac aging father fixated on his digestive tract, and an impatient cab company owner.",
        "release_date": datetime.date(2015, 5, 8),
        "runtime_minutes": 123,
        "vote_average": 7.9,
        "vote_count": 6700,
        "popularity": 80.0,
        "director": "Shoojit Sircar",
        "cast_members": "Deepika Padukone, Amitabh Bachchan, Irrfan Khan, Moushumi Chatterjee",
        "poster_path": "https://image.tmdb.org/t/p/w500/y9M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/z1M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "genres": ["Comedy", "Drama"],
        "keywords": "Bollywood, Indian Cinema, Hindi, Family, Road Trip, Chill",
    },
    {
        "title": "RRR",
        "type": "movie",
        "overview": "In 1920s British-occupied India, two legendary revolutionaries form a transcendent friendship without knowing each other's secret identities before embarking on an epic war of liberation.",
        "release_date": datetime.date(2022, 3, 24),
        "runtime_minutes": 182,
        "vote_average": 8.2,
        "vote_count": 14000,
        "popularity": 95.0,
        "director": "S.S. Rajamouli",
        "cast_members": "N.T. Rama Rao Jr., Ram Charan, Alia Bhatt, Ajay Devgn",
        "poster_path": "https://image.tmdb.org/t/p/w500/wE0noMt24BsEi9vF3V4utgN9K9h.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/7c9UVPPiTPltouxSh26AQ83xPtC.jpg",
        "genres": ["Action", "Drama", "Adventure"],
        "keywords": "Bollywood, Indian Cinema, Telugu, Hindi, Epic, High Octane, Action",
    },
    {
        "title": "The Lunchbox",
        "type": "movie",
        "overview": "A mistaken delivery in Mumbai's famously meticulous dabbawala lunchbox system connects a neglected housewife with an aging widower on the verge of retirement via handwritten notes.",
        "release_date": datetime.date(2013, 9, 20),
        "runtime_minutes": 104,
        "vote_average": 7.8,
        "vote_count": 6200,
        "popularity": 79.0,
        "director": "Ritesh Batra",
        "cast_members": "Irrfan Khan, Nimrat Kaur, Nawazuddin Siddiqui, Bharati Achrekar",
        "poster_path": "https://image.tmdb.org/t/p/w500/a2M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/b3M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "genres": ["Romance", "Drama"],
        "keywords": "Bollywood, Indian Cinema, Hindi, Warm, Contemplative, Mumbai",
    },
    # --- ACCLAIMED BOLLYWOOD SERIES ---
    {
        "title": "Sacred Games",
        "type": "series",
        "overview": "A troubled Mumbai police officer receives an anonymous tip from an elusive crime boss who warns him that the entire city will be obliterated in 25 days.",
        "release_date": datetime.date(2018, 7, 6),
        "runtime_minutes": 50,
        "vote_average": 8.5,
        "vote_count": 8700,
        "popularity": 91.0,
        "director": "Anurag Kashyap, Vikramaditya Motwane",
        "cast_members": "Saif Ali Khan, Nawazuddin Siddiqui, Radhika Apte, Pankaj Tripathi",
        "poster_path": "https://image.tmdb.org/t/p/w500/c4M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/d5M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "genres": ["Crime", "Drama", "Thriller"],
        "keywords": "Bollywood, Indian Cinema, Hindi, Series, Dark Suspense, Mumbai",
    },
    {
        "title": "Panchayat",
        "type": "series",
        "overview": "An engineering graduate takes up a low-paying secretary job in a remote Uttar Pradesh village panchayat due to a lack of better job options, experiencing endearing rural realities.",
        "release_date": datetime.date(2020, 4, 3),
        "runtime_minutes": 35,
        "vote_average": 8.8,
        "vote_count": 9500,
        "popularity": 93.0,
        "director": "Deepak Kumar Mishra",
        "cast_members": "Jitendra Kumar, Neena Gupta, Raghubir Yadav, Chandan Roy, Faisal Malik",
        "poster_path": "https://image.tmdb.org/t/p/w500/e6M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/f7M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "genres": ["Comedy", "Drama"],
        "keywords": "Bollywood, Indian Cinema, Hindi, Series, Rural, Chill, Feel-Good",
    },
    {
        "title": "Mirzapur",
        "type": "series",
        "overview": "The iron-fisted mafia don and carpet exporter Kaleen Bhaiya rules Mirzapur, but an incident at a wedding ignites a violent clash with two righteous brothers.",
        "release_date": datetime.date(2018, 11, 16),
        "runtime_minutes": 55,
        "vote_average": 8.4,
        "vote_count": 9100,
        "popularity": 92.0,
        "director": "Karan Anshuman, Gurmmeet Singh",
        "cast_members": "Pankaj Tripathi, Ali Fazal, Divyenndu, Shweta Tripathi, Rasika Dugal",
        "poster_path": "https://image.tmdb.org/t/p/w500/g8M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/h9M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "genres": ["Crime", "Action", "Thriller"],
        "keywords": "Bollywood, Indian Cinema, Hindi, Series, Mafia, High Octane, Gritty",
    },
    {
        "title": "The Family Man",
        "type": "series",
        "overview": "Srikant Tiwari, a middle-class man who secretly works as a world-class spy for the National Investigation Agency, balances national counter-terror operations with domestic family life.",
        "release_date": datetime.date(2019, 9, 20),
        "runtime_minutes": 45,
        "vote_average": 8.7,
        "vote_count": 8900,
        "popularity": 92.0,
        "director": "Raj & DK",
        "cast_members": "Manoj Bajpayee, Priyamani, Sharib Hashmi, Samantha Ruth Prabhu",
        "poster_path": "https://image.tmdb.org/t/p/w500/i1M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/j2M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "genres": ["Action", "Comedy", "Drama"],
        "keywords": "Bollywood, Indian Cinema, Hindi, Series, Espionage, Thriller, Witty",
    },
    # --- ACCLAIMED GLOBAL COMEDIES & FEEL-GOOD TITLES ---
    {
        "title": "Superbad",
        "type": "movie",
        "overview": "Two codependent high school seniors plan to score alcohol for a raging party to impress their crushes before heading off to different colleges, descending into riotous chaos.",
        "release_date": datetime.date(2007, 8, 17),
        "runtime_minutes": 113,
        "vote_average": 7.8,
        "vote_count": 13500,
        "popularity": 86.0,
        "director": "Greg Mottola",
        "cast_members": "Jonah Hill, Michael Cera, Christopher Mintz-Plasse, Bill Hader, Seth Rogen",
        "poster_path": "https://image.tmdb.org/t/p/w500/ek8e8txUyUwd2BNqj6lFEerJ9ix.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/foc5RcsdKz32B5F1q3w8xH8Z4f.jpg",
        "genres": ["Comedy"],
        "keywords": "Hollywood, Teen, High School, Party, Chill, Friends",
    },
    {
        "title": "The Hangover",
        "type": "movie",
        "overview": "Three buddies wake up from a bachelor party in Las Vegas with no memory of the previous night and the bachelor missing. They must retrace their wild steps around town to find him.",
        "release_date": datetime.date(2009, 6, 5),
        "runtime_minutes": 100,
        "vote_average": 7.7,
        "vote_count": 16000,
        "popularity": 85.0,
        "director": "Todd Phillips",
        "cast_members": "Bradley Cooper, Ed Helms, Zach Galifianakis, Justin Bartha, Ken Jeong",
        "poster_path": "https://image.tmdb.org/t/p/w500/uluhlXubGu1VxU63X9VgUtIWNW.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/4fChVq2w0S7M7v6Y7m8V9b5m7m7.jpg",
        "genres": ["Comedy"],
        "keywords": "Hollywood, Vegas, Bachelor Party, Mystery, Friends, Chill",
    },
    {
        "title": "La La Land",
        "type": "movie",
        "overview": "While navigating their careers in Los Angeles, a dedicated jazz pianist and an aspiring actress fall in love, but must face the sacrifices required to pursue their dreams.",
        "release_date": datetime.date(2016, 12, 9),
        "runtime_minutes": 128,
        "vote_average": 8.0,
        "vote_count": 16500,
        "popularity": 88.0,
        "director": "Damien Chazelle",
        "cast_members": "Ryan Gosling, Emma Stone, John Legend, J.K. Simmons",
        "poster_path": "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkVJt0Rf0.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/hu18v5dO2O5v1V9b5m7m7m7m7m7.jpg",
        "genres": ["Comedy", "Drama", "Romance"],
        "keywords": "Hollywood, Musical, Los Angeles, Date Night, Feel-Good",
    },
    {
        "title": "Paddington 2",
        "type": "movie",
        "overview": "Paddington takes on a series of odd jobs to buy a unique pop-up book for his Aunt Lucy's 100th birthday, only for the book to be stolen by a villainous master of disguise.",
        "release_date": datetime.date(2017, 11, 10),
        "runtime_minutes": 103,
        "vote_average": 8.1,
        "vote_count": 9200,
        "popularity": 87.0,
        "director": "Paul King",
        "cast_members": "Ben Whishaw, Hugh Grant, Sally Hawkins, Hugh Bonneville",
        "poster_path": "https://image.tmdb.org/t/p/w500/q0nhn17X5V5v1V9b5m7m7m7m7m7.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/r1nhn17X5V5v1V9b5m7m7m7m7m7.jpg",
        "genres": ["Comedy", "Adventure", "Animation"],
        "keywords": "Family, Feel-Good, London, Heartwarming, Chill",
    },
    {
        "title": "Ted Lasso",
        "type": "series",
        "overview": "An American college football coach is hired to manage a struggling British soccer team, winning over the cynical squad and town with his relentless optimism and homemade biscuits.",
        "release_date": datetime.date(2020, 8, 14),
        "runtime_minutes": 32,
        "vote_average": 8.7,
        "vote_count": 8200,
        "popularity": 92.0,
        "director": "Brendan Hunt, Joe Kelly",
        "cast_members": "Jason Sudeikis, Hannah Waddingham, Brett Goldstein, Juno Temple",
        "poster_path": "https://image.tmdb.org/t/p/w500/s4M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "backdrop_path": "https://image.tmdb.org/t/p/original/t5M1K9b6V7oX9b5m7m7m7m7m7m7.jpg",
        "genres": ["Comedy", "Drama"],
        "keywords": "Series, Sports, Football, Feel-Good, Chill, Uplifting",
    }
]


OTT_PROVIDER_MAP = {
    "Interstellar": "Amazon Prime Video, Netflix",
    "Blade Runner 2049": "Amazon Prime Video, Netflix",
    "Parasite": "Amazon Prime Video, Disney+ Hotstar",
    "Knives Out": "Amazon Prime Video, Netflix",
    "The Dark Knight": "Amazon Prime Video, Netflix",
    "Pulp Fiction": "Amazon Prime Video",
    "Whiplash": "Netflix",
    "Inception": "Amazon Prime Video, Netflix",
    "Spirited Away": "Netflix",
    "The Grand Budapest Hotel": "Disney+ Hotstar",
    "Breaking Bad": "Netflix",
    "Stranger Things": "Netflix",
    "Succession": "Disney+ Hotstar, JioCinema",
    "Severance": "Apple TV+",
    "Chernobyl": "Disney+ Hotstar, JioCinema",
    "The Bear": "Disney+ Hotstar",
    "Fleabag": "Amazon Prime Video",
    "3 Idiots": "Netflix, Amazon Prime Video",
    "Zindagi Na Milegi Dobara": "Netflix, Amazon Prime Video",
    "Dangal": "Disney+ Hotstar, Netflix",
    "Andhadhun": "Netflix",
    "Tumbbad": "Amazon Prime Video",
    "Gangs of Wasseypur": "Netflix",
    "Dil Chahta Hai": "Netflix, Amazon Prime Video",
    "Taare Zameen Par": "Netflix",
    "Queen": "Netflix",
    "Drishyam": "Disney+ Hotstar, Netflix",
    "Barfi!": "Netflix",
    "Chhichhore": "Disney+ Hotstar",
    "Stree": "Disney+ Hotstar, Netflix",
    "Kahaani": "Amazon Prime Video",
    "Jab We Met": "Amazon Prime Video, Netflix",
    "Piku": "SonyLIV, Amazon Prime Video",
    "RRR": "Netflix, Disney+ Hotstar",
    "The Lunchbox": "Netflix",
    "Sacred Games": "Netflix",
    "Panchayat": "Amazon Prime Video",
    "Mirzapur": "Amazon Prime Video",
    "The Family Man": "Amazon Prime Video",
    "Superbad": "Netflix",
    "The Hangover": "Amazon Prime Video, Netflix",
    "La La Land": "Amazon Prime Video, Netflix",
    "Paddington 2": "Amazon Prime Video, Netflix",
    "Ted Lasso": "Apple TV+",
}


def seed_database_if_empty(db: Session):
    """Populate genres and titles if not already present, and ensure OTT providers are populated."""
    # Seed genres
    existing_genres = {g.name: g for g in db.query(Genre).all()}
    for name in SEED_GENRES:
        if name not in existing_genres:
            genre = Genre(name=name)
            db.add(genre)
    db.commit()

    # Re-fetch all genres
    db_genres = {g.name: g for g in db.query(Genre).all()}

    # Seed titles (insert any title that does not already exist)
    existing_titles = {t.title for t in db.query(Title.title).all()}
    for raw_item in SEED_TITLES:
        title_name = raw_item["title"]
        if title_name in existing_titles:
            continue
        item = dict(raw_item)
        genre_names = item.pop("genres", [])
        if "ott_providers" not in item and title_name in OTT_PROVIDER_MAP:
            item["ott_providers"] = OTT_PROVIDER_MAP[title_name]
        title = Title(**item)
        for g_name in genre_names:
            if g_name in db_genres:
                title.genres.append(db_genres[g_name])
        db.add(title)
    db.commit()

    # Update existing titles that lack ott_providers
    db_all_titles = db.query(Title).all()
    for t in db_all_titles:
        if not t.ott_providers and t.title in OTT_PROVIDER_MAP:
            t.ott_providers = OTT_PROVIDER_MAP[t.title]
    db.commit()

